{
  inputs = {
    v_flakes.url = "github:valeratrades/v_flakes?ref=v1.6";
  };

  outputs = { self, v_flakes }:
    let
      inherit (v_flakes) flake-utils pre-commit-hooks;
    in
    flake-utils.lib.eachDefaultSystem (
      system:
      let
        pkgs = import v_flakes.default_nixpkgs {
          inherit system;
          config.allowUnfree = true;
        };
        # Canonical toolchain pinned in v_flakes — byte-identical across repos, so
        # the nix store dedups it and sccache cross-references compilations.
        rust = v_flakes.rs.default_nightly system;
        pre-commit-check = pre-commit-hooks.lib.${system}.run (v_flakes.files.preCommit { inherit pkgs; });
        manifest = (pkgs.lib.importTOML ./Cargo.toml).package;
        pname = manifest.name;
        stdenv = pkgs.stdenvAdapters.useMoldLinker pkgs.stdenv;

        # Pinned to match the workspace's `wasm-bindgen` (`=0.2.126`) — nixpkgs
        # ships a different minor, and a CLI/crate schema skew is a hard error at
        # `wasm-bindgen` time. Shadows `pkgs.wasm-bindgen-cli` (a `let` binding
        # wins over `with pkgs;`) wherever it's referenced below.
        wasm-bindgen-cli =
          let
            src = pkgs.fetchCrate {
              pname = "wasm-bindgen-cli";
              version = "0.2.126";
              hash = "sha256-H6Is3fiZVxZCfOMWK5dWMSrtn50VGv0sfdnsT+cTtyk=";
            };
          in
          pkgs.buildWasmBindgenCli {
            inherit src;
            cargoDeps = pkgs.rustPlatform.fetchCargoVendor {
              inherit src;
              inherit (src) pname version;
              hash = "sha256-VucqkXbCi4qtQzY/HrXiDnbSURsagPsdNVMn1Tw3UiY=";
            };
          };

        rs = v_flakes.rs {
          inherit pkgs rust;
          build.enable = false;
          # getrandom 0.3 (transitive via v_utils -> ustr -> ahash) needs the wasm_js
          # backend on wasm. Paired with the `wasm_js` feature in
          # [target.wasm32-unknown-unknown.dependencies] in Cargo.toml.
          targets."wasm32-unknown-unknown".rustflags = [ "--cfg" ''getrandom_backend="wasm_js"'' ];
        };
        github = v_flakes.github {
          inherit pkgs pname rs;
          enable = true;
          lastSupportedVersion = "nightly-${v_flakes.rs.nightly_version}";
          containerRelease = { registry = "ghcr.io/valeratrades"; };
          jobs.default = true;
          lfs = true;
          # regenerated by the rs module on every shell entry; carries machine-local
          # accelerators (sccache wrapper) that break plain-rustup CI runners if committed
          gitignore.extra = ''
            .cargo/config.toml
          '';
        };
        readme = v_flakes.readme-fw {
          inherit pkgs pname;
          defaults = true;
          lastSupportedVersion = "nightly-1.92";
          rootDir = ./.;
          badges = [ "msrv" "loc" "ci" ];
        };
        combined = v_flakes.utils.combine { inherit rust; modules = [ rs github readme ]; };
      in
      let
        build_rust = v_flakes.rs.build_nightly system;
        rustPlatform = pkgs.makeRustPlatform {
          rustc = build_rust;
          cargo = build_rust;
          inherit stdenv;
        };
        # `.cargo` holds dev-only accelerators (sccache rustc-wrapper, cranelift,
        # mold) the hermetic sandbox lacks — drop it so the pure build uses nix's
        # own toolchain. The one thing it carried that the build DOES need (the
        # getrandom wasm_js cfg) is re-exported in the wasm build step below.
        pureSrc = pkgs.lib.cleanSourceWith {
          src = ./.;
          filter = path: _type: baseNameOf path != ".cargo";
        };
        # v_utils' `lightweight_charts` feature `include_str!`s this, and its build.rs would `curl`
        # it — which the hermetic sandbox forbids. Fetched here instead (a fixed-output derivation,
        # the one place network is allowed) and handed over via `LWC_MJS`. Version and hash must
        # match the crate's own pin; a mismatch fails its assert rather than reaching a browser.
        lightweightCharts = pkgs.fetchurl {
          url = "https://cdn.jsdelivr.net/npm/lightweight-charts@5.2.0/dist/lightweight-charts.standalone.production.mjs";
          sha256 = "66ac22df1b08de08ec2fae2b401b0f9731a4653a28e18a9837c7c3553c33dbe2";
        };
        siteBin = rustPlatform.buildRustPackage {
          inherit pname;
          version = manifest.version;

          # No `.git` in the hermetic sandbox — hand build.rs the commit for the BuildTag.
          SITE_BUILD_REV = self.shortRev or self.dirtyShortRev or "";
          LWC_MJS = lightweightCharts;

          src = pureSrc;
          cargoLock = {
            lockFile = ./Cargo.lock;
            outputHashes = {
              "leptos-routable-0.2.0" = "sha256-w17sr9fLbUaCHP6x/fVSmR5dYduTGBlXBDna7Ksq+ZM=";
            };
          };

          buildInputs = with pkgs; [ openssl.dev ];
          nativeBuildInputs = with pkgs; [
            pkg-config
            wasm-bindgen-cli
            binaryen
          ];

          # Server binary and WASM client are separate compilations (ssr vs hydrate
          # features), so cargo-leptos is bypassed: plain cargo + wasm-bindgen + wasm-opt.
          buildPhase = ''
            runHook preBuild

            cargo build --release --bin ${pname} --features ssr --no-default-features

            RUSTFLAGS='--cfg getrandom_backend="wasm_js"' \
              cargo build --release --lib --target wasm32-unknown-unknown --features hydrate --no-default-features

            mkdir -p target/site/pkg
            wasm-bindgen --target web \
              --out-dir target/site/pkg \
              --out-name ${pname} \
              target/wasm32-unknown-unknown/release/${pname}.wasm

            wasm-opt -Oz target/site/pkg/${pname}_bg.wasm -o target/site/pkg/${pname}_bg.wasm

            runHook postBuild
          '';

          installPhase = ''
            runHook preInstall

            mkdir -p $out/bin $out/share/${pname}
            cp target/release/${pname} $out/bin/${pname}-unwrapped
            cp -r target/site/pkg $out/share/${pname}/pkg
            cp -r public/* $out/share/${pname}/

            cat > $out/bin/${pname} <<EOF
            #!${pkgs.runtimeShell}
            export LEPTOS_SITE_ROOT="\''${LEPTOS_SITE_ROOT:-$out/share/${pname}}"
            exec "$out/bin/${pname}-unwrapped" "\$@"
            EOF
            chmod +x $out/bin/${pname}

            runHook postInstall
          '';

          doCheck = false;
          auditable = false; # cargo-auditable doesn't support edition 2024
        };

        # Container entrypoint. The binary resolves everything relative to cwd:
        # `Cargo.toml` (leptos config), `public/blog` (typ sources, compiled at
        # runtime — hence typst in runtimeInputs) and `target/site/blog` (compiled
        # html output, read back server-side — needs write). So stage a writable
        # cwd in /data (the persistent mount) with the read-only pieces symlinked
        # from the store. HOME=/data puts the sqlite db + dashboard caches (XDG
        # paths) on the same mount.
        # Not in the image: the cluster mounts it as a ConfigMap (devops), editable while running.
        # Secrets come from the container's env through `{ env = … }`.
        prodConfig = (pkgs.formats.toml { }).generate "site.toml" {
          site_url = "https://valeratrades.com";
          google_oauth = {
            client_id = "350565753492-iltccminubv2bi8b6m1355mdsdmo6238.apps.googleusercontent.com";
            client_secret = { env = "GOOGLE_CLIENT_SECRET"; };
          };
          sso = {
            signing_key_pem = { env = "SSO_SIGNING_KEY_PEM"; };
            cookie_domain = "valeratrades.com";
          };
          groups = {
            admin = [ "v79166789533@gmail.com" "valeratrades@gmail.com" ];
            service-arb = [ "v79166789533@gmail.com" ];
          };
        };
        prodRun = pkgs.writeShellApplication {
          name = "${pname}-prod";
          runtimeInputs = with pkgs; [ coreutils typst ];
          text = ''
            mkdir -p /data/public /data/target/site
            cd /data
            ln -sfn ${siteBin}/share/${pname}/blog public/blog
            ln -sfn ${./Cargo.toml} Cargo.toml
            export LEPTOS_SITE_ADDR="''${LEPTOS_SITE_ADDR:-0.0.0.0:61156}"
            export LEPTOS_ENV=PROD
            : "''${1:?usage: ${pname}-prod --config <site.toml>}"
            exec ${siteBin}/bin/${pname} "$@"
          '';
        };
        # `nix run .#dev` → `cargo leptos watch`, from anywhere in the repo.
        # Resolve the repo at runtime (`git rev-parse`), never `toString ./.`:
        # the latter locks the wrapper to the read-only /nix/store snapshot where
        # cargo can't write target/. Delegates to `nix develop` since cargo-leptos
        # (version-pinned to the leptos crate, installed on shell entry) and the
        # .cargo/config.toml accelerators live in the devShell, not this bare app.
        runDev = pkgs.writeShellApplication {
          name = "run-dev";
          runtimeInputs = [ pkgs.git ];
          text = ''
            repo="$(git rev-parse --show-toplevel)"
            cd "$repo"
            exec nix develop "$repo" --command cargo leptos watch
          '';
        };
        # ── bump latest remote vX.Y.Z tag and push: `.#publish major|minor|patch` ──
        runPublish = pkgs.writeShellApplication {
          name = "publish";
          runtimeInputs = [ pkgs.git ];
          text = ''
            part="''${1:-}"
            case "$part" in major|minor|patch) ;; *) echo "usage: nix run .#publish -- major|minor|patch" >&2; exit 1 ;; esac
            [ -z "$(git status --porcelain)" ] || { echo "uncommitted changes — commit or stash first" >&2; exit 1; }

            git fetch --tags --force origin >/dev/null 2>&1
            last="$(git tag -l 'v*' --sort=-v:refname | head -n1)"
            ver="''${last#v}"; [ -n "$ver" ] || ver="0.0.0"
            IFS=. read -r ma mi pa <<EOF
            $ver
            EOF
            case "$part" in
              major) ma=$((ma+1)); mi=0; pa=0 ;;
              minor) mi=$((mi+1)); pa=0 ;;
              patch) pa=$((pa+1)) ;;
            esac
            next="v$ma.$mi.$pa"
            echo "$last → $next"
            git tag "$next"
            git push origin "$next"
          '';
        };
        containerStd = v_flakes.container.implement {
          inherit pkgs pname;
          containers."" = {
            port = 61156;
            healthPath = "/";
            criticality = "normal";
            entrypoint = [ "${prodRun}/bin/${pname}-prod" ];
            mounts = [ "/data" ];
            workingDir = "/data";
            imageEnv = [ "HOME=/data" ];
            sqlite = [ "/data/.local/state/site/db.sqlite3" ];
          };
        };
      in
      {
        packages = {
          default = siteBin;
          prod-config = prodConfig;
        } // containerStd.packages;

        containers = containerStd.containers;

        apps = {
          default = {
            type = "app";
            program = "${siteBin}/bin/${pname}";
          };
          dev = {
            type = "app";
            program = "${runDev}/bin/run-dev";
          };
          publish = {
            type = "app";
            program = "${runPublish}/bin/publish";
          };
        };

        devShells.default = pkgs.mkShell {
          inherit stdenv;
          shellHook =
            pre-commit-check.shellHook
            + combined.shellHook
            + ''
              cp -f ${(v_flakes.files.treefmt) { inherit pkgs; }} ./.treefmt.toml

              # cargo-leptos must match leptos crate's version; thus can't install through nixpkgs
              # Use a lock file to ensure only one terminal installs it
              LOCK_FILE="/tmp/cargo-leptos-install-$(echo "$PWD" | md5sum | cut -d' ' -f1).lock"
              if mkdir "$LOCK_FILE" 2>/dev/null; then
                trap "rmdir '$LOCK_FILE' 2>/dev/null" EXIT
                if grep -qi ubuntu /etc/os-release 2>/dev/null; then
                  cargo binstall -y cargo-leptos
                else
                  cargo install cargo-leptos
                fi
              fi
            '';

          packages = with pkgs; [
            mold
            openssl
            pkg-config
            perl
            sccache
            rust
            binaryen
            typst # blog .typ -> .html compilation at server runtime
            wasm-bindgen-cli # manual client builds — must match wasm-bindgen =0.2.126
          ] ++ pre-commit-check.enabledPackages ++ combined.enabledPackages;

          env.RUST_BACKTRACE = 1;
          env.RUST_LIB_BACKTRACE = 0;
        };
      }
    );
}
