{
  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";
    flake-utils.url = "github:numtide/flake-utils";
    pre-commit-hooks.url = "github:cachix/git-hooks.nix";
    pre-commit-hooks.inputs.nixpkgs.follows = "nixpkgs";
    v_flakes.url = "github:valeratrades/v_flakes?ref=v1.6";
    v_flakes.inputs.nixpkgs.follows = "nixpkgs";
  };

  outputs = { self, nixpkgs, flake-utils, pre-commit-hooks, v_flakes }:
    flake-utils.lib.eachDefaultSystem (
      system:
      let
        pkgs = import nixpkgs {
          inherit system;
          config.allowUnfree = true;
        };
        # Canonical toolchain pinned in v_flakes — byte-identical across repos, so
        # the nix store dedups it and sccache cross-references compilations.
        rust = v_flakes.rs.default_nightly system;
        pre-commit-check = pre-commit-hooks.lib.${system}.run (v_flakes.files.preCommit { inherit pkgs; });
        manifest = (pkgs.lib.importTOML ./Cargo.toml).package;
        pname = manifest.name;
        stdenv = pkgs.stdenvAdapters.useMoldLinker pkgs.stdenv;

        # Pinned to match the workspace's `wasm-bindgen` (`=0.2.126`) — nixpkgs
        # ships a different minor, and a CLI/crate schema skew is a hard error at
        # `wasm-bindgen` time. Shadows `pkgs.wasm-bindgen-cli` (a `let` binding
        # wins over `with pkgs;`) wherever it's referenced below.
        wasm-bindgen-cli =
          let
            src = pkgs.fetchCrate {
              pname = "wasm-bindgen-cli";
              version = "0.2.126";
              hash = "sha256-H6Is3fiZVxZCfOMWK5dWMSrtn50VGv0sfdnsT+cTtyk=";
            };
          in
          pkgs.buildWasmBindgenCli {
            inherit src;
            cargoDeps = pkgs.rustPlatform.fetchCargoVendor {
              inherit src;
              inherit (src) pname version;
              hash = "sha256-VucqkXbCi4qtQzY/HrXiDnbSURsagPsdNVMn1Tw3UiY=";
            };
          };

        rs = v_flakes.rs {
          inherit pkgs rust;
          build.enable = false;
          # getrandom 0.3 (transitive via v_utils -> ustr -> ahash) needs the wasm_js
          # backend on wasm. Paired with the `wasm_js` feature in
          # [target.wasm32-unknown-unknown.dependencies] in Cargo.toml.
          targets."wasm32-unknown-unknown".rustflags = [ "--cfg" ''getrandom_backend="wasm_js"'' ];
        };
        github = v_flakes.github {
          inherit pkgs pname rs;
          enable = true;
          lastSupportedVersion = "nightly-2026-06-16";
          containerRelease = { registry = "ghcr.io/valeratrades"; };
          jobs.default = true;
          lfs = true;
          # regenerated by the rs module on every shell entry; carries machine-local
          # accelerators (sccache wrapper) that break plain-rustup CI runners if committed
          gitignore.extra = ''
            .cargo/config.toml
          '';
        };
        readme = v_flakes.readme-fw {
          inherit pkgs pname;
          defaults = true;
          lastSupportedVersion = "nightly-1.92";
          rootDir = ./.;
          badges = [ "msrv" "loc" "ci" ];
        };
        combined = v_flakes.utils.combine { inherit rust; modules = [ rs github readme ]; };
      in
      let
        rustc = rust;
        cargo = rust;
        rustPlatform = pkgs.makeRustPlatform {
          inherit rustc cargo stdenv;
        };
        # `.cargo` holds dev-only accelerators (sccache rustc-wrapper, cranelift,
        # mold) the hermetic sandbox lacks — drop it so the pure build uses nix's
        # own toolchain. The one thing it carried that the build DOES need (the
        # getrandom wasm_js cfg) is re-exported in the wasm build step below.
        pureSrc = pkgs.lib.cleanSourceWith {
          src = ./.;
          filter = path: _type: baseNameOf path != ".cargo";
        };
        siteBin = rustPlatform.buildRustPackage {
          inherit pname;
          version = manifest.version;

          src = pureSrc;
          cargoLock = {
            lockFile = ./Cargo.lock;
            outputHashes = {
              "leptos-routable-0.2.0" = "sha256-w17sr9fLbUaCHP6x/fVSmR5dYduTGBlXBDna7Ksq+ZM=";
            };
          };

          buildInputs = with pkgs; [ openssl.dev ];
          nativeBuildInputs = with pkgs; [
            pkg-config
            wasm-bindgen-cli
            binaryen
          ];

          # Server binary and WASM client are separate compilations (ssr vs hydrate
          # features), so cargo-leptos is bypassed: plain cargo + wasm-bindgen + wasm-opt.
          buildPhase = ''
            runHook preBuild

            cargo build --release --bin ${pname} --features ssr --no-default-features

            RUSTFLAGS='--cfg getrandom_backend="wasm_js"' \
              cargo build --release --lib --target wasm32-unknown-unknown --features hydrate --no-default-features

            mkdir -p target/site/pkg
            wasm-bindgen --target web \
              --out-dir target/site/pkg \
              --out-name ${pname} \
              target/wasm32-unknown-unknown/release/${pname}.wasm

            wasm-opt -Oz target/site/pkg/${pname}_bg.wasm -o target/site/pkg/${pname}_bg.wasm

            runHook postBuild
          '';

          installPhase = ''
            runHook preInstall

            mkdir -p $out/bin $out/share/${pname}
            cp target/release/${pname} $out/bin/${pname}-unwrapped
            cp -r target/site/pkg $out/share/${pname}/pkg
            cp -r public/* $out/share/${pname}/

            cat > $out/bin/${pname} <<EOF
            #!/bin/sh
            export LEPTOS_SITE_ROOT="\''${LEPTOS_SITE_ROOT:-$out/share/${pname}}"
            exec "$out/bin/${pname}-unwrapped" "\$@"
            EOF
            chmod +x $out/bin/${pname}

            runHook postInstall
          '';

          doCheck = false;
          auditable = false; # cargo-auditable doesn't support edition 2024
        };

        # Container entrypoint. The binary resolves everything relative to cwd:
        # `Cargo.toml` (leptos config), `public/blog` (typ sources, compiled at
        # runtime — hence typst in runtimeInputs) and `target/site/blog` (compiled
        # html output, read back server-side — needs write). So stage a writable
        # cwd in /data (the persistent mount) with the read-only pieces symlinked
        # from the store. HOME=/data puts the sqlite db + dashboard caches (XDG
        # paths) on the same mount.
        prodRun = pkgs.writeShellApplication {
          name = "${pname}-prod";
          runtimeInputs = with pkgs; [ typst ];
          text = ''
            mkdir -p /data/public /data/target/site
            cd /data
            ln -sfn ${siteBin}/share/${pname}/blog public/blog
            ln -sfn ${./Cargo.toml} Cargo.toml
            export LEPTOS_SITE_ADDR="''${LEPTOS_SITE_ADDR:-0.0.0.0:61156}"
            export LEPTOS_ENV=PROD
            exec ${siteBin}/bin/${pname}
          '';
        };
        containerStd = v_flakes.container.implement {
          inherit pkgs pname;
          containers."" = {
            port = 61156;
            healthPath = "/";
            criticality = "normal";
            entrypoint = [ "${prodRun}/bin/${pname}-prod" ];
            mounts = [ "/data" ];
            workingDir = "/data";
            imageEnv = [ "HOME=/data" ];
          };
        };
      in
      {
        packages = {
          default = siteBin;
        } // containerStd.packages;

        containers = containerStd.containers;

        apps.default = {
          type = "app";
          program = "${siteBin}/bin/${pname}";
        };

        devShells.default = pkgs.mkShell {
          inherit stdenv;
          shellHook =
            pre-commit-check.shellHook
            + combined.shellHook
            + ''
              cp -f ${(v_flakes.files.treefmt) { inherit pkgs; }} ./.treefmt.toml

              # cargo-leptos must match leptos crate's version; thus can't install through nixpkgs
              # Use a lock file to ensure only one terminal installs it
              LOCK_FILE="/tmp/cargo-leptos-install-$(echo "$PWD" | md5sum | cut -d' ' -f1).lock"
              if mkdir "$LOCK_FILE" 2>/dev/null; then
                trap "rmdir '$LOCK_FILE' 2>/dev/null" EXIT
                if grep -qi ubuntu /etc/os-release 2>/dev/null; then
                  cargo binstall -y cargo-leptos
                else
                  cargo install cargo-leptos
                fi
              fi
            '';

          packages = with pkgs; [
            mold
            openssl
            pkg-config
            perl
            sccache
            rust
            binaryen
            typst # blog .typ -> .html compilation at server runtime
            wasm-bindgen-cli # manual client builds — must match wasm-bindgen =0.2.126
          ] ++ pre-commit-check.enabledPackages ++ combined.enabledPackages;

          env.RUST_BACKTRACE = 1;
          env.RUST_LIB_BACKTRACE = 0;
        };
      }
    );
}
